# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/satoshi_watanabe/dev/kakehashi/zxing-cpp/wrappers/wasm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/satoshi_watanabe/dev/kakehashi/zxing-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.20.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.20.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.20.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.20.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.20.5/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.20.5/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/satoshi_watanabe/dev/kakehashi/zxing-cpp/CMakeFiles /Users/satoshi_watanabe/dev/kakehashi/zxing-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/satoshi_watanabe/dev/kakehashi/zxing-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zxing_writer

# Build rule for target.
zxing_writer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zxing_writer
.PHONY : zxing_writer

# fast build rule for target.
zxing_writer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing_writer.dir/build.make CMakeFiles/zxing_writer.dir/build
.PHONY : zxing_writer/fast

#=============================================================================
# Target rules for targets named zxing_reader

# Build rule for target.
zxing_reader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zxing_reader
.PHONY : zxing_reader

# fast build rule for target.
zxing_reader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing_reader.dir/build.make CMakeFiles/zxing_reader.dir/build
.PHONY : zxing_reader/fast

#=============================================================================
# Target rules for targets named zxing

# Build rule for target.
zxing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zxing
.PHONY : zxing

# fast build rule for target.
zxing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing.dir/build.make CMakeFiles/zxing.dir/build
.PHONY : zxing/fast

#=============================================================================
# Target rules for targets named ZXing

# Build rule for target.
ZXing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZXing
.PHONY : ZXing

# fast build rule for target.
ZXing/fast:
	$(MAKE) $(MAKESILENT) -f ZXing/CMakeFiles/ZXing.dir/build.make ZXing/CMakeFiles/ZXing.dir/build
.PHONY : ZXing/fast

BarcodeReader.o: BarcodeReader.cpp.o
.PHONY : BarcodeReader.o

# target to build an object file
BarcodeReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing_reader.dir/build.make CMakeFiles/zxing_reader.dir/BarcodeReader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing.dir/build.make CMakeFiles/zxing.dir/BarcodeReader.cpp.o
.PHONY : BarcodeReader.cpp.o

BarcodeReader.i: BarcodeReader.cpp.i
.PHONY : BarcodeReader.i

# target to preprocess a source file
BarcodeReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing_reader.dir/build.make CMakeFiles/zxing_reader.dir/BarcodeReader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing.dir/build.make CMakeFiles/zxing.dir/BarcodeReader.cpp.i
.PHONY : BarcodeReader.cpp.i

BarcodeReader.s: BarcodeReader.cpp.s
.PHONY : BarcodeReader.s

# target to generate assembly for a file
BarcodeReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing_reader.dir/build.make CMakeFiles/zxing_reader.dir/BarcodeReader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing.dir/build.make CMakeFiles/zxing.dir/BarcodeReader.cpp.s
.PHONY : BarcodeReader.cpp.s

BarcodeWriter.o: BarcodeWriter.cpp.o
.PHONY : BarcodeWriter.o

# target to build an object file
BarcodeWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing_writer.dir/build.make CMakeFiles/zxing_writer.dir/BarcodeWriter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing.dir/build.make CMakeFiles/zxing.dir/BarcodeWriter.cpp.o
.PHONY : BarcodeWriter.cpp.o

BarcodeWriter.i: BarcodeWriter.cpp.i
.PHONY : BarcodeWriter.i

# target to preprocess a source file
BarcodeWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing_writer.dir/build.make CMakeFiles/zxing_writer.dir/BarcodeWriter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing.dir/build.make CMakeFiles/zxing.dir/BarcodeWriter.cpp.i
.PHONY : BarcodeWriter.cpp.i

BarcodeWriter.s: BarcodeWriter.cpp.s
.PHONY : BarcodeWriter.s

# target to generate assembly for a file
BarcodeWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing_writer.dir/build.make CMakeFiles/zxing_writer.dir/BarcodeWriter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zxing.dir/build.make CMakeFiles/zxing.dir/BarcodeWriter.cpp.s
.PHONY : BarcodeWriter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ZXing"
	@echo "... zxing"
	@echo "... zxing_reader"
	@echo "... zxing_writer"
	@echo "... BarcodeReader.o"
	@echo "... BarcodeReader.i"
	@echo "... BarcodeReader.s"
	@echo "... BarcodeWriter.o"
	@echo "... BarcodeWriter.i"
	@echo "... BarcodeWriter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

